### ISSUE TITLE
Week 1 Tasks

### ISSUE THREAD

**Issue by stas97** [stas97/transformers-group-octupus#1]
- [x] Create a git repository
- [x]  Make sure that all team members have write access to the github repository
- [x]  Create a dedicated environment for you project to keep track of your packages
- [x]  Create the initial file structure using cookiecutter
- [x]  Fill out the make_dataset.py file such that it downloads whatever data you need and
- [x]  Add a model file and a training script and get that running
- [x]  When you have something that works somewhat, remember at some point to to some profiling and see if you can optimize your code
- [x]  Remember to fill out the requirement.py file with whatever dependencies that you are using
- [ ]  Write unit tests for some part of the codebase and calculate the
- [x]  Get some continues integration running on the github repository
- [ ]  use either tensorboard or wandb to log training progress and other important metrics/artifacts in your code
- [ ]  remember to comply with good coding practices while doing the project

**Comment by stas97** [comment]
- [ ] Create a dedicated environment
 This is user specific, right? So we just make sure to add all packages we use to `requirements.txt` and run this setup in our environments.

**Comment by marcoplacenti** [comment]
@marcoplacenti working on making dataset

**Comment by stas97** [comment]
@stas97 has copy-pasta'ed some workflows that are not yet specific to our project. Basically, only the `isort` workflow runs. 
I will implement those as we go on with tests and stuff.

**Comment by marcoplacenti** [comment]
@marcoplacenti has finished the data load script. Right now it's in the branch `dev_marco` and no pull request has been done yet.

The file is called `fetch_dataset.py` instead of `make_dataset.py`, as I thought that the latter can be used to take the data from `raw/` (that the former creates), into `processed/` ready for training.

To download the dataset, from root run `python src/data/fetch_dataset.py config/datasets_to_merge.json`

`datasets_to_merge.json` is a file in which you can specify what datasets you want to merge together into one big file. Write 1 to include the file, 0 to exclude. Have a look at it, it should be quite straightforward.

The flow of the code:

- check if the desired datasets have been previously been downloaded and extracted
- if the datasets have never been downloaded, then download the binary files into `external/`
- extract the binary files and store the `.csv` into `interim/`
- ensemble the desired datasets sitting in `interim/` into a big file called `AmazonProductReviews.csv` stored in `raw/`
- empty `interim/`

Hope I didn't miss anything! :)

**Comment by stas97** [comment]
Go ahead and create a PR if you're happy with it. I am out climbing but will look at it later.

**Comment by bh1995** [comment]
@bh1995 working on training a model

**Comment by marcoplacenti** [comment]
@bh1995 let me know if you have an idea on how the data should be transformed from raw to be training-ready - like format, file extension, etc.

**Comment by bh1995** [comment]
@marcoplacenti I made a function that cleans the data and sets it into a DataLoader format, I'm just trying to figure out how to set all the paths  so the functions run nicely from terminal. I am a bit of a noob at this stuff haha

**Comment by marcoplacenti** [comment]
Sorry I didn't get the notification of your message D: 
If you have not solved and if you have not done this: first and foremost, I think you need to place yourself at the root and run `pip install -e .`
Make sure you have the most recent master into your dev branch. Then, still from root, you need to run `python src/data/fetch_dataset.py config/datasets_to_merge.json`. This will download the dataset into `raw/` if you don't have it already. By default it will download and merge the Automotive.csv and Patio_Lawn_and_Garden.csv files. You can change what file to download from config/dataset_to_merge.json

Now in your script you can read the data doing 
`with open('data/raw/AmazonProductReviews.csv') as f: blablabla`.

Remember to run your script from root also.

**Comment by bh1995** [comment]
I have created a new dev branch which has scripts to load clean and run inference on the AmazonProductReviews data. You can use them by running `python src/models/predict_model.py` from root. 

There is a problem however, the weights file for the BERT model is too large (420 MB) to push to github. Does anyone have any ideas on what to do about this?

I have not set up cloud training yet, so for now I trained the model locally for a short time and also saved the weights locally. For the script to work, just put the weights file into the `transformers-group-octupus/models` folder. The weights can be downloaded here: [https://drive.google.com/file/d/1mP7JIaqK4JDl_Lehg_FVJJxXXwltfovh/view?usp=sharing](url) .

**Comment by marcoplacenti** [comment]
Nice! If it's ok with everyone, I can take care of implementing the functionality to run the train on cloud - I did it with MNIST so it shouldn't take long. Or are you already working on it?

Not really have a solution for the BERT model size, but I'll look around a bit and see if I can come up with suggestions.

**Comment by stas97** [comment]
Can I do it? 😌
I mean, I can.. but is it okay with you guys if I have my fun with it a bit?

**Comment by marcoplacenti** [comment]
Sure thing, it's fine by me :) have fun! And reach out if you run into issues! I've had a couple, so I might be able to help you.

@bh1995 your code looks good! However, I think that your `clean_data` script is supposed to go into `src/data/make_dataset.py` and rather than returning something, it should write it into the `data/processed/` folder. Then, you can read from `data/processed` when training/predicting or whatever. What do you guys think?

**Comment by bh1995** [comment]
@stas97 Go for it if you have a good feeling (y). 

@marcoplacenti Yes, that could be a better long term solution than returning something. I'll change it a bit later tonight.

Another solution for the weights could be to just find a smaller architecture, I think there is a small BERT architecture too. But I feel there must be some work around for larger files on github.

**Comment by marcoplacenti** [comment]
I move the open tasks to the week 2 issue, so I'm closing this one.
